FROM node:4-onbuild


#RUN mkdir -p /home/docker

#RUN sudo apt-get -y update && sudo apt-get -y upgrade
#RUN sudo apt-get install -y python curl


#ENTRYPOINT ["/bin/sh", "/home/docker/entrypoint.sh"]
